name: Testing Self-Hosted Runner
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: [self-hosted, Windows, devops]
    steps:
      - name: Echo Content
        run: |
          echo Ok
          Start-Sleep -Seconds 15
