name: Variable Secrets Workflow

on:
  #workflow_dispatch:
    
  #schedule:
    #- cron: "*/1 * * * *" # दररोज मध्यरात्री चालवण्यासाठी क्रॉन शेड्यूल
  [push]

# 🌍 WORKFLOW LEVEL VARIABLES
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    # प्रकार १: GitHub Variable आणि Environment Variable एकत्र वापरणे
    - name: Docker Build
      run: |
        echo "Building image using GitHub Context..."
        echo "Command: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

    # प्रकार २: GitHub Secret आणि Variable वापरून लॉगिन करणे
    - name: Docker Login
      run: |
        echo "Logging into Registry...."
        # vars.ने युझरनेम आणि secrets.ने पासवर्ड कॉल केला आहे
        echo "Command: docker login --username ${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}"

    - name: Docker Publish
      run: |
        echo "Pushing image to registry..."
        echo "Command: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

  # दुसरा जॉब (इथेही आपण व्हॅल्यूज चेक करू शकतो)
  deploy:
    if: github.ref == 'refs/heads/main' # फक्त मुख्य ब्रांचवर पुश झाल्यावर डिप्लॉय होईल
    needs: docker
    concurrency:
      group: deploy-job
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      timeout-minutes: 1
      run: |
        echo "Deploying the image built in previous job..."
        echo "Target Image: ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
        sleep 6000s