name: Variable Secrets Workflow

on: [push]

# 🌍 WORKFLOW LEVEL VARIABLES (हे संपूर्ण फाईलमध्ये कुठेही वापरता येतील)
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    # प्रकार १: GitHub च्या सिंटॅक्सने व्हेरिएबल्स वापरणे (सर्वात सुरक्षित पद्धत)
    - name: Docker Build
      run: |
        echo "Building image using GitHub Context..."
        echo "Command: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME }}:latest"

    # प्रकार २: Step Level Variable आणि Linux Environment Variable वापरणे
    - name: Docker Login
      # 🧪 STEP LEVEL VARIABLE (हा फक्त याच स्टेपपुरता मर्यादित आहे)
      run: |
        echo "Logging into Registry...."
        # गिटहब वरचे ग्लोबल env व्हेरिएबल्स लिनक्स शेलमध्ये थेट $ ने सुद्धा एक्सेस करता येतात
        echo "Command: docker login --username $DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: |
        echo "Pushing image to registry..."
        echo "Command: docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME }}:latest"

  # दुसरा जॉब (हा फक्त हे तपासण्यासाठी आहे की ग्लोबल व्हेरिएबल्स इथे चालतात की नाही)
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Verify Global Variables in Deploy Job
      run: |
        echo "Deploying the image built in previous job..."
        echo "Target Image: ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/${{ env.IMAGE_NAME }}:latest"