name: Variable Secrets Workflow

on: [push]

# 🌍 WORKFLOW LEVEL VARIABLES
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v4

    # प्रकार १: GitHub Variable आणि Environment Variable एकत्र वापरणे
    - name: Docker Build
      run: |
        echo "Building image using GitHub Context..."
        echo "Command: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

    # प्रकार २: GitHub Secret आणि Variable वापरून लॉगिन करणे
    - name: Docker Login
      run: |
        echo "Logging into Registry...."
        # vars.ने युझरनेम आणि secrets.ने पासवर्ड कॉल केला आहे
        echo "Command: docker login --username ${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}"

    - name: Docker Publish
      run: |
        echo "Pushing image to registry..."
        echo "Command: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

  # दुसरा जॉब (इथेही आपण व्हॅल्यूज चेक करू शकतो)
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Verify Global Variables in Deploy Job
      run: |
        echo "Deploying the image built in previous job..."
        echo "Target Image: ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"